{% set version = "0.1.5" %}

package:
    name: metheor
    version: {{ version }}

source:
    git_url: https://github.com/JianmeiZhong/metheor

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - rust
        # - clangdev
        # - pkg-config
        # - make
        - cmake

    run:
        - rust

about:
    home: https://github.com/JianmeiZhong/metheor
